### PR TITLE
Adding install Clear Linux

### PR DESCRIPTION
**Pull request by thiagottjv**

### CODE REVIEW

**Comment by fiveangle** [comment]
@thiagottjv - it looks like you have just a placeholder in this PR to non-existant doc, and then only the doc in your patch-2 branch but no update to the readme.md ?
 
 https://github.com/thiagottjv/chia-plotter/blob/patch-2/doc/install_clearlinux.md

**Comment by madMAx43v3r** [comment]
yeah he forgot to commit the file

**Comment by thiagottjv** [comment]
> yeah he forgot to commit the file

Yes... I do that on PR #308... I should haver done them together

**Comment by madMAx43v3r** [comment]
got it

**Pull request merged**
