### PR TITLE
GitHub Actions CI Build

### PR DESCRIPTION
**Pull request by Randomblock1**
Builds a release and debug binary every time you push a commit.

### CODE REVIEW

**Comment by madMAx43v3r** [comment]
interesting, for ubuntu 20.04?

**Comment by VertiHydro** [comment]
> interesting, for ubuntu 20.04?

From this page: https://github.com/actions/virtual-environments
Ubuntu-latest does refer to 20.04, so yes.

**Comment by devedse** [comment]
Would it also be possible to add Windows Compilation? Or is that still broken?

**Comment by madMAx43v3r** [comment]
cool stuff, lets try it then

**Comment by jneuhauser** [comment]
@Randomblock1 Can you also add a link to the readme to download the latest release builld?

**Comment by Randomblock1** [comment]
> Would it also be possible to add Windows Compilation? Or is that still broken?

The only Windows instructions I see are for running a Docker container.

Until Windows is _officially supported_ (which may or may not ever happen) I don't want builds failing.

I could probably set up a Docker building action, though...

**Pull request merged**
