### PR TITLE
add some support

### PR DESCRIPTION
**Pull request by dendil**
add some support ，and modified some scripts

### CODE REVIEW

**Review by mist0706 — APPROVED** [review]
Looks good

**Comment by madMAx43v3r** [comment]
https://github.com/cwpearson/llvmvm/issues/1

**Comment by madMAx43v3r** [comment]
> nproc not available on macOS

**Comment by dendil** [comment]
Sorry ，I cant use macOS  ， try use      **nproc=`cat /proc/cpuinfo |grep processor|wc -l `

**Comment by madMAx43v3r** [comment]
I don't have one either, just saying it should work there also.. quite some ppl are using it on mac

**Comment by zyzzyva99** [comment]
`sysctl -n hw.logicalcpu` is equivalent to `nproc` on Mac.

**Comment by madMAx43v3r** [comment]
if you remove the `nproc` again we can merge it, it's not worth it anyways, the main binary takes the most time to compile

**Pull request merged**
