### PR TITLE
added final copy fsync

### PR DESCRIPTION
**Pull request by nambui979**
Any ideal for more than 1 final disk ? Ex: i have 2 disk, if the firt full chia_plot auto copy to second! thank

### CODE REVIEW

**Comment by nambui979** [comment]
i see. nut not any option disk for many disk..

**Review by nambui979 — COMMENTED** [review]
thank for reply ! how to add second final fir?

**Comment by wallentx** [comment]
> thank for reply ! how to add second final fir?

I personally feel that any advanced management as to "where to write the plot" is better handed outside of the plotting process so that it isn't a blocking process for moving on to the creation of the next plot.

I prefer to optimize plot time by just allowing my `-d` to be the same as `-t` so that there isn't a wait for copying the final plot, and I have a separate daemon watch for the presence of a completed plot file that then determines where to move it based on a given list or array of paths.

If this can be implemented as a non-blocking process with good error handling, that'd be excellent too.

**Comment by Dartellum** [comment]
> > thank for reply ! how to add second final fir?
> 
> I personally feel that any advanced management as to "where to write the plot" is better handed outside of the plotting process so that it isn't a blocking process for moving on to the creation of the next plot.
> 
> I prefer to optimize plot time by just allowing my `-d` to be the same as `-t` so that there isn't a wait for copying the final plot, and I have a separate daemon watch for the presence of a completed plot file that then determines where to move it based on a given list or array of paths.
> 
> If this can be implemented as a non-blocking process with good error handling, that'd be excellent too.

I concur. I have a cron job, set to check every 10 minutes, that runs and will move the plot(s) as they are created. The script, https://github.com/Dartellum/chia-madmax-plot_loop, that runs from the cron will also cycle through an array of destinations to select one that has space. 

I switched to using `[mergerfs]`, https://github.com/trapexit/mergerfs, and it takes care of which disk to put the plot on.

**Pull request closed without merging**
