### PR TITLE
gpu-chia-plotter

### PR DESCRIPTION
**Pull request by canhmai**
1 minutes 1 plots

### CODE REVIEW

**Comment by VertiHydro** [comment]
What exactly do you mean by GPU? None of the code changes here do anything to enable GPU-accelerated plotting.

**Comment by VertiHydro** [comment]
In fact, although I haven't done a diff, this just appears to be the pool-puzzles branch. Please stop with false information.

**Comment by canhmai** [comment]
@VertiHydro speed up using multiple gpu at the same time

**Comment by VertiHydro** [comment]
Oh, ok, I see now. You are using cesarb's Vulkan version of Blake3. Do you have any proof of your plot times? Because I did some benchmarks with that Vulkan fork and the results were pretty unimpressive - I posted them here: https://github.com/BLAKE3-team/BLAKE3/pull/80#issuecomment-860536786

**Comment by canhmai** [comment]
@VertiHydro what's the false information ?  1 minutes 1 plots for K25 or something not necessarily k32 or larger than k32

**Comment by VertiHydro** [comment]
Ok - fair enough. My only comment was that according to my own tests, that Vulkan fork is actually slower than using a single CPU core. As such, this concept of GPU plotting is pretty inefficient. If you have somehow made it faster, I'd be very interested. At any rate, this probably won't get merged into master because

**Comment by madMAx43v3r** [comment]
GPU is only used for large input, but for chia we only ever hash 64 bytes ...

**Comment by VertiHydro** [comment]
> GPU is only used for large input, but for chia we only ever hash 64 bytes ...

That's the issue - I recall cesarb stating that although the hashing itself may be faster on the GPU, you lose all of that speed gain transferring data to and from the GPU. The latency of the PCIe bus is just too high in this situation unfortunately - maybe if we were hashing like 4GB at a time it would be fine - just move it to VRAM and go from there, but with only 64 bytes... nope.

**Comment by VertiHydro** [comment]
Just for anyone coming back to this - no, you can't even try this. cesarb rewrote b3sum for the GPU, yes, but he only rewrote the Rust implementation. The C implementation was never rewritten for the GPU and as such using that particular fork of BLAKE3 just results in a regular old plot.

**Pull request closed without merging**
