### PR TITLE
[README] [Update] G option readme update

### PR DESCRIPTION
**Pull request by Dartellum**
Put some wording around the -G option usage in the Readme. If it is wrong, please let me know so I can correct it. The wording is how I understand it works. 

I have remove trailing spaces set on, that is why the other lines are changed.

### CODE REVIEW

**Comment by VertiHydro** [comment]
It looks good - but did you mean to also change the copy.h file? Is it possible that you are using an old or modified version of the plotter?

**Comment by madMAx43v3r** [comment]
yeah he merge the fsync branch

**Comment by Dartellum** [comment]
> It looks good - but did you mean to also change the copy.h file? Is it possible that you are using an old or modified version of the plotter?

Weird, when I did it locally it was on the one file, README, that was changed. I checked with git status before committing. I will see what happened and correct it.

**Comment by madMAx43v3r** [comment]
when you go to the `commits` tab it'll show "Merge remote-tracking branch 'upstream/fsync-final-copy'".

To fix it, make a new clone of the repo, copy the readme in it, make a new commit + pull request.

**Comment by madMAx43v3r** [comment]
I've added it myself, thx.

**Pull request closed without merging**
