### PR TITLE
GitHub Actions Docker build & push

### PR DESCRIPTION
**Pull request by Randomblock1**
This automatically builds a Docker image every time you commit, and pushes it to Docker Hub with the commit hash as the tag and sets it to 'master'.
Every time you create a GitHub release, it will tag that with its git tag and sets the 'latest' tag to it.
Also, pull requests will trigger a build but will not push. (for obvious reasons.)
See it in action [here](https://hub.docker.com/repository/docker/randomblock1/chia-plotter).

You need to add some GitHub Secrets for it to work properly.
Go to repo Settings, Secrets, and add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN. After that, it will work properly.

### CODE REVIEW

**Comment by madMAx43v3r** [comment]
I'll check it out

**Comment by delucca** [comment]
> I'll check it out

Hey @madMAx43v3r, if you don't want to configure a Dockerhub account I could set up this PR to automatically deploy in mine. Just let me know :)

**Comment by madMAx43v3r** [comment]
yeah let's do that

**Comment by delucca** [comment]
> yeah let's do that

Cool :)

To do that, I would need to configure settings in the chia-plotter repository. Probably if I'm added as a team member I can create secrets in it

**Comment by delucca** [comment]
@madMAx43v3r I'm still not being able to see the `Settings` section of the repository. Probably only the owner can see that.

Can I send those secrets for you on Discord? Then you can add them and I'll manage to finish the rest of the integration.

Also, @Randomblock1, since you've already coded the Action, could you please just add another tag in the image? Typically in full CI/CD applications I suggest tagging with `latest` but also with the Git hash. Could you please add that to the PR too?

**Comment by Randomblock1** [comment]
@delucca 
Tagging is currently as follows:
- Sha hash for every commit
- `master` corresponds to the latest sha hash
- Will automatically produce tags from Git tags (and GitHub Releases)
- `latest` corresponds to the latest Git tag

The `master` tag is the latest commit. The `latest` tag is the latest Git tag. So if you want the `latest` tag to be updated, create a Git tag (something like v1.0).

It is built in to docker/metadata-action, so that's why you didn't notice it in the Actions file.

**Comment by delucca** [comment]
> @delucca
> Tagging is currently as follows:
> 
>     * Sha hash for every commit
> 
>     * `master` corresponds to the latest sha hash
> 
>     * Will automatically produce tags from Git tags (and GitHub Releases)
> 
>     * `latest` corresponds to the latest Git tag
> 
> 
> The `master` tag is the latest commit. The `latest` tag is the latest Git tag. So if you want the `latest` tag to be updated, create a Git tag (something like v1.0).
> 
> It is built in to docker/metadata-action, so that's why you didn't notice it in the Actions file.

Cool!

Just waiting @madMAx43v3r decide regarding the secret, them I'll talk with him over Discord to merge this PR. Thanks!

**Comment by madMAx43v3r** [comment]
yeah just send it over discord

**Comment by delucca** [comment]
> yeah just send it over discord

Just sent it to you over Discord 😄

**Comment by delucca** [comment]
@Randomblock1 could you please commit something to trigger the action again? Just to check if it is now working ;)

**Comment by Randomblock1** [comment]
Huh, weird. Some edit to the Dockerfile broke it. I think the line with `git submodule update` needs to be removed, or we need to make sure `.git` is copied to Docker. Either one works.

**Comment by Randomblock1** [comment]
Well, apparently `.git` doesn't exist or Docker doesn't want to use it in GitHub runners.
The README includes instructions to do a submodule update anyway, though, so it's not really an issue.

**Comment by Randomblock1** [comment]
There are now Docker build instructions, and because it was getting a little cramped, I put everything in expandable dropdowns. It also builds fine now, and [the `latest` tag does indeed work.](https://hub.docker.com/layers/randomblock1/chia-plotter/latest/images/sha256-595a48248d8acf5a33eeb12c0209b69c99fbd9ae8d250f1c130dc8ad4e135ade?context=repo)

**Comment by delucca** [comment]
@Randomblock1 actually, you would need the submodules init to be executed either inside the Docker container, or before launching the `docker build` command. That is mandatory, if you don't do that, the binary won't compile

Also, I've noticed that you accidently rolled back some files to the previous version (specifically the `README.md` file), could you please checkout the newest version please?

**Comment by delucca** [comment]
Oh, never mind what I said about the `README` file, now I understood that you intended to change that.

IMHO I think the best approach would be creating an `INSTALL.md` file (separate from `README.md` and link that file in the `README.md` file. What do you think @madMAx43v3r ?

**Comment by Randomblock1** [comment]
It is building correctly, but you cannot do a git submodule update in the Dockerfile if you want GitHub Actions to work, so I put instructions for that in the Docker section.

**Comment by madMAx43v3r** [comment]
so how is it getting the submodules then?

**Comment by madMAx43v3r** [comment]
INSTALL.md should be a separate pull request

**Comment by Randomblock1** [comment]
The GitHub Actions file clones with the `recursive` option, which means it clones dependencies immediately after it clones the main project.

I'll revert the README and make a new PR

**Comment by madMAx43v3r** [comment]
ah I see, makes sense

**Comment by delucca** [comment]
> ah I see, makes sense
> 
> @delucca how about doing the same for Docker?

IMHO I don't Docker would need to know anything regarding the submodule init. We could add a section explaining how to build your own Docker image, but most users would use the image we're providing.

Regarding the `INSTALL.md` file, I think that should be a different PR too!

**Comment by delucca** [comment]
Well, anyway, can we merge it @madMAx43v3r? LGTM :)

**Review by delucca — APPROVED** [review]

**Comment by madMAx43v3r** [comment]
let's do it then

**Comment by delucca** [comment]
@Randomblock1 it seems that the workflow had a few errors, do you know if everything is working accordingly?

**Comment by Randomblock1** [comment]
It's trying to push to madmax43v3r/chia-plotter, but that doesn't exist in Docker Hub. Either an account with that name wasn't created, or an image with that name wasn't created. If you want to use a different username or image name, you'll need to edit the Actions file.

**Comment by delucca** [comment]
> @delucca It's trying to push to madmax43v3r/chia-plotter, but that doesn't exist in Docker Hub. Either an account with that name wasn't created, or an image with that name wasn't created. If you want to use a different username or image name, you'll need to edit the Actions file.

Ah thanks, I'm going to fix that!

**Pull request merged**
