### PR TITLE
Phase 2 double threads toggle option

### PR DESCRIPTION
**Pull request by madMAx43v3r**

### CODE REVIEW

**Comment by malventano** [comment]
Anything else needed for this toggle to make it into master? It should help plotting speeds on tmp constrained / high core count systems that are otherwise limited to only a single instance of the plotter (e.g. server plotting with tmpfs, etc).

**Comment by madMAx43v3r** [comment]
yeah need to add a cmd line switch

**Comment by malventano** [comment]
recommend -m as it is effectively just a multiplier, and you might eventually expand on that if enabling adjustment of threads on other phases.

**Comment by malventano** [comment]
Looks like this branches off of master prior to pool puzzles, so anyone checking out this branch should be aware that it does not include -c option.

**Pull request merged**
