### PR TITLE
Upgrade Blake lib to latest, Improve speed on Table1.

### PR DESCRIPTION
**Pull request by SKlayer**
Upgrade Blake lib to latest(https://github.com/BLAKE3-team/BLAKE3/tree/master/c), Improve Phase1Table1 speed from 15.6s to 13.38s

### CODE REVIEW

**Comment by GTANAdam** [comment]
How much improvement are we talking about?

**Comment by madMAx43v3r** [comment]
Table 1 doesn't use BLAKE, but I will check it out.

**Comment by madMAx43v3r** [comment]
If you revert the CMakeLists.txt whitespace changes, we could squash and merge it.

**Comment by madMAx43v3r** [comment]
Also I would have to review all the code changes to make sure there is no hidden code. It's easier if I copy the code myself..

**Comment by madMAx43v3r** [comment]
see  #59

**Comment by madMAx43v3r** [comment]
I tested with latest BLAKE3, didn't gain much, ~5 sec in phase 1.

**Comment by SKlayer** [comment]
> I tested with latest BLAKE3, didn't gain much, ~5 sec in phase 1.

improvement in windows is even greater because of the additional assembly code

**Pull request closed without merging**
