### PR TITLE
staging and final destination

### PR DESCRIPTION
**Pull request by tomrippity**
Can there not be a staging drive to quickly get the plot off of tmp and move it onto a fast storage space and then have a final phase that will move the plot to long term storage while having already started the next plot, if desired?

This is about the only advantage that swar has at the moment. I can set a temporary destination and a final and have it start the new job as soon as it is in its temp destination.

### CODE REVIEW

**Comment by VertiHydro** [comment]
> Can there not be a staging drive to quickly get the plot off of tmp and move it onto a fast storage space and then have a final phase that will move the plot to long term storage while having already started the next plot, if desired?
> 
> This is about the only advantage that swar has at the moment. I can set a temporary destination and a final and have it start the new job as soon as it is in its temp destination.

I'm not sure why you have opened a pull request for what seems to be a question - did you mean to do that? Anyway, I'll answer the question. The answer is that this functionality already exists: I assume your reasoning for wanting it is so that the plots won't get held up waiting for the previous plot to be copied. Well, fear not: the final destination feature implemented into the plotter runs the copy operations in the background, which means when one plot finishes it will immediately begin a new plot while transferring the old plot in the background so there is no waiting around.

**Comment by carlos-sardina** [comment]
> > Can there not be a staging drive to quickly get the plot off of tmp and move it onto a fast storage space and then have a final phase that will move the plot to long term storage while having already started the next plot, if desired?
> > This is about the only advantage that swar has at the moment. I can set a temporary destination and a final and have it start the new job as soon as it is in its temp destination.
> 
> I'm not sure why you have opened a pull request for what seems to be a question - did you mean to do that? Anyway, I'll answer the question. The answer is that this functionality already exists: I assume your reasoning for wanting it is so that the plots won't get held up waiting for the previous plot to be copied. Well, fear not: the final destination feature implemented into the plotter runs the copy operations in the background, which means when one plot finishes it will immediately begin a new plot while transferring the old plot in the background so there is no waiting around.

This info could be in README lot of users are not aware about this

**Comment by tomrippity** [comment]
> > Can there not be a staging drive to quickly get the plot off of tmp and move it onto a fast storage space and then have a final phase that will move the plot to long term storage while having already started the next plot, if desired?
> > This is about the only advantage that swar has at the moment. I can set a temporary destination and a final and have it start the new job as soon as it is in its temp destination.
> 
> I'm not sure why you have opened a pull request for what seems to be a question - did you mean to do that? Anyway, I'll answer the question. The answer is that this functionality already exists: I assume your reasoning for wanting it is so that the plots won't get held up waiting for the previous plot to be copied. Well, fear not: the final destination feature implemented into the plotter runs the copy operations in the background, which means when one plot finishes it will immediately begin a new plot while transferring the old plot in the background so there is no waiting around.

Sorry, I didn't mean to comment in the wrong spot.
I'm also not sure I clearly explained the desired functionality.
In my mind, the process should work as follows.

Plotting happens on tmp1&2 drives.
Plot is moved to a very fast staging space (maybe a another small nvme or ssd)
New job kicks off
Plot is moved from staging space to long term location.

As it is right now, I believe it just goes from the working space to the final destination, which is okay at the end of the day, but it means that my work temp space has io competition while it moves the finished plot to the final destination.  It takes about 15-20 minutes to go from an NVME to an HDD, but if I could go to another temporary NVME first, my working space could be done transferring in maybe 2 minutes and have all of its IO available.

**Comment by VertiHydro** [comment]
> > > Can there not be a staging drive to quickly get the plot off of tmp and move it onto a fast storage space and then have a final phase that will move the plot to long term storage while having already started the next plot, if desired?
> > > This is about the only advantage that swar has at the moment. I can set a temporary destination and a final and have it start the new job as soon as it is in its temp destination.
> > 
> > 
> > I'm not sure why you have opened a pull request for what seems to be a question - did you mean to do that? Anyway, I'll answer the question. The answer is that this functionality already exists: I assume your reasoning for wanting it is so that the plots won't get held up waiting for the previous plot to be copied. Well, fear not: the final destination feature implemented into the plotter runs the copy operations in the background, which means when one plot finishes it will immediately begin a new plot while transferring the old plot in the background so there is no waiting around.
> 
> Sorry, I didn't mean to comment in the wrong spot.
> I'm also not sure I clearly explained the desired functionality.
> In my mind, the process should work as follows.
> 
> Plotting happens on tmp1&2 drives.
> Plot is moved to a very fast staging space (maybe a another small nvme or ssd)
> New job kicks off
> Plot is moved from staging space to long term location.
> 
> As it is right now, I believe it just goes from the working space to the final destination, which is okay at the end of the day, but it means that my work temp space has io competition while it moves the finished plot to the final destination. It takes about 15-20 minutes to go from an NVME to an HDD, but if I could go to another temporary NVME first, my working space could be done transferring in maybe 2 minutes and have all of its IO available.

Ok, I see what you mean. I'm not sure if this would actually improve anything, but it might. This functionality, however, will likely not be added to the plotter as it adds too much additional complexity. The best way to do what you describe is to set the staging NVMe as your final directory, and then write a script that checks whenever a file enters the staging directory and automatically moves it to the HDD.

**Comment by tomrippity** [comment]
> Ok, I see what you mean. I'm not sure if this would actually improve anything, but it might. This functionality, however, will likely not be added to the plotter as it adds too much additional complexity. The best way to do what you describe is to set the staging NVMe as your final directory, and then write a script that checks whenever a file enters the staging directory and automatically moves it to the HDD.

I believe it would.  I've noticed that when I run mad max the first time through it always completes 3 or 4 minutes faster.  My subsequent plots are all slower, so I believe it is related to the drive having competition for its IO.  Certainly possible its related to something else.  

I appreciate your responses.

**Comment by phillq** [comment]
> > Ok, I see what you mean. I'm not sure if this would actually improve anything, but it might. This functionality, however, will likely not be added to the plotter as it adds too much additional complexity. The best way to do what you describe is to set the staging NVMe as your final directory, and then write a script that checks whenever a file enters the staging directory and automatically moves it to the HDD.
> 
> I believe it would. I've noticed that when I run mad max the first time through it always completes 3 or 4 minutes faster. My subsequent plots are all slower, so I believe it is related to the drive having competition for its IO. Certainly possible its related to something else.
> 
> I appreciate your responses.

Now it all makes sense why my first plot is so much faster then the rest - temp1 = 10K SAS RAID0 so IO would be going like crazy copying from a mechanical disk to my final dir while in Phase 1 doing the next plot.

**Comment by GTANAdam** [comment]
This is unneeded.

**Comment by madMAx43v3r** [comment]
sorry this cannot be merged

**Pull request closed without merging**
