### PR TITLE
K33 version

### PR DESCRIPTION
**Pull request by SNGDude**
Now plots create as K33 data.

### CODE REVIEW

**Comment by Hardcore-fs** [comment]
I thought this was supposed to be a massive amount of work ,instead of changing just 1 code line?

**Comment by VertiHydro** [comment]
@madMAx43v3r surely it cannot be this easy?

**Comment by VertiHydro** [comment]
> @madMAx43v3r surely it cannot be this easy?

I feel like this is some kind of joke because they removed all the instructions

**Comment by Hardcore-fs** [comment]
just testing it now........
I think it is bull.....
there is no difference it plotting time......
plus i don't see the code "auto adapting" to a larger array, basically it's just a bigger array
then not utilized.

**Comment by Hardcore-fs** [comment]
well if it is a "joke" its gonna be on him... by the time i have finished with him

**Comment by Hardcore-fs** [comment]
> > @madMAx43v3r surely it cannot be this easy?
> 
> I feel like this is some kind of joke because they removed all the instructions

well if it is a "joke" its gonna be on him... by the time i have finished with him

**Comment by VertiHydro** [comment]
> just testing it now........
> I think it is bull.....
> there is no difference it plotting time......
> plus i don't see the code "auto adapting" to a larger array, basically it's just a bigger array
> then not utilized.
> 
> nope file is exactly the same size & same processing time.
> 
> 108,821,664,318 bytes (108.82 GB on disk)
> 
> bobzzz
> 
> the plot checker reports it as size 32

Yep exactly as expected

**Comment by madMAx43v3r** [comment]
lol that's not how it works, the seed is always 32 bytes, `k` is something totally different

**Pull request closed without merging**
