### PR TITLE
Adds macOS section to README.

### PR DESCRIPTION
**Pull request by AndriiHlukhanyk**

### CODE REVIEW

**Comment by moertel187** [comment]
Tried it, get lots of Errors on step ./make_devel.sh
/Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:15:1: error: unknown directive .intel_syntax noprefix ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:15:1: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:15:1: error: unknown directive .intel_syntax noprefix ^ error: unknown directive .intel_syntax noprefix ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:32:9: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:27:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:31:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r15 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:15:1: error: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:33:9: error: unknown directive unrecognized instruction mnemonic, did you mean: ushl, ushr? error: .intel_syntax noprefix push r15 ^ unrecognized instruction mnemonic, did you mean: ushl, ushr? ^ push r14 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:31:9/Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S: :28:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:34:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? error: error: push r15 unrecognized instruction mnemonic, did you mean: ushl, ushr? unrecognized instruction mnemonic, did you mean: ushl, ushr? push r15 push r13 ^ ^ ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S/Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S::3532::99: : error: error: unrecognized instruction mnemonic, did you mean: ushl, ushr? unrecognized instruction mnemonic, did you mean: ushl, ushr? push r12 push r14 ^ ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:33:9: push r14 ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r13 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:29:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:32:9: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:34:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? error: push r13 ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r12 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:30:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:36:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:35:9: error: error: push r14 error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push rbx unrecognized instruction mnemonic, did you mean: ushl, ushr?
and so on

**Comment by AndriiHlukhanyk** [comment]
> Tried it, get lots of Errors on step ./make_devel.sh
> 
> /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:15:1: error: unknown directive .intel_syntax noprefix ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:15:1: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:15:1: error: unknown directive .intel_syntax noprefix ^ error: unknown directive .intel_syntax noprefix ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:32:9: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:27:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:31:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r15 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:15:1: error: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:33:9: error: unknown directive unrecognized instruction mnemonic, did you mean: ushl, ushr? error: .intel_syntax noprefix push r15 ^ unrecognized instruction mnemonic, did you mean: ushl, ushr? ^ push r14 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:31:9/Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S: :28:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:34:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? error: error: push r15 unrecognized instruction mnemonic, did you mean: ushl, ushr? unrecognized instruction mnemonic, did you mean: ushl, ushr? push r15 push r13 ^ ^ ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S/Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S::3532::99: : error: error: unrecognized instruction mnemonic, did you mean: ushl, ushr? unrecognized instruction mnemonic, did you mean: ushl, ushr? push r12 push r14 ^ ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:33:9: push r14 ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r13 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:29:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse41_x86-64_unix.S:32:9: error: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:34:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? error: push r13 ^ error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push r12 ^ /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx2_x86-64_unix.S:30:9: /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_avx512_x86-64_unix.S:36:9: unrecognized instruction mnemonic, did you mean: ushl, ushr? /Users/Kaspersky/chia-plotter/lib/BLAKE3/c/blake3_sse2_x86-64_unix.S:35:9: error: error: push r14 error: unrecognized instruction mnemonic, did you mean: ushl, ushr? push rbx unrecognized instruction mnemonic, did you mean: ushl, ushr?
> 
> and so on

Tried this on few Intel Macs with Big Sur - didn't get any errors. Unfortunately, I don't have M1 Mac, so I'm not sure what causes this issue.

**Comment by madMAx43v3r** [comment]
CMakeLists.txt needs to be fixed to detect ARM reliably

**Comment by madMAx43v3r** [comment]
should be fixed in latest master

**Pull request merged**
