### PR TITLE
Added pool puzzle hash option

### PR DESCRIPTION
**Pull request by madMAx43v3r**

### CODE REVIEW

**Comment by madMAx43v3r** [comment]
anybody know how to get a puzzle hash? maybe try on testnet

**Comment by dhongki** [comment]
> _No description provided._

Hello, will it invalidate all plots created before this?

**Comment by madMAx43v3r** [comment]
no it wont, it's an alternate way to create plots for pools

**Comment by Magister** [comment]
> anybody know how to get a puzzle hash? maybe try on testnet

I think you need to install Chia from `pools.dev` branch maybe, there are some `pools.xxx` branches around in the repo, not sure which one is correct.

**Comment by l-we** [comment]
branch pools.dev
chia plotnft create -u https://farm-testnet.pool.garden/
chia plotnft show
-z P2 singleton address

**Comment by l-we** [comment]
```(venv) root@Gateway:/home/chia-blockchain# ls -lh /home/tmp/
总用量 105G
-rw-r--r-- 1 root root 2.8G 6月  18 09:23 plot-k27-2021-06-18-09-00-123a9a902a0c9b912edd80177ccbb3fc6613aaa77fddfd2bca20f691b7d3f858.plot
-rw-r--r-- 1 root root 102G 6月  18 12:51 plot-k32-2021-06-18-09-47-b8a479e61c56233b2f43b6fa8fb8bce8a92d3bd86a433919a541b08bf0d38d9e.plot
(venv) root@Gateway:/home/chia-blockchain# chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Harvester 127.0.0.1:45736:
   2 plots of size: 104.060 GiB
Plot count for all harvesters: 2
Total size of plots: 104.060 GiB
Estimated network space: 253.916 TiB
Expected time to win: 10 hours and 9 minutes
```

**Comment by madMAx43v3r** [comment]
great news, thanks for testing it

**Comment by altendky** [comment]
Is `-z` here the same as `-c`/`--pool_contract_address` for `chia plots create`?  It seems like it based on my understanding but I'm no expert in this area, just trying to get plotman ready for pools (with multiple plotters).

```
  -c, --pool_contract_address TEXT
                                  Address of where the pool reward will be
                                  sent to. Only used if alt_fingerprint and
                                  pool public key are None
```

**Comment by madMAx43v3r** [comment]
no it's not the same...

**Comment by madMAx43v3r** [comment]
Seems like I need to convert the `pool contract address` to the puzzle has via: https://github.com/Chia-Network/chia-blockchain/blob/538227acc10a5c24cbc2d169a1076ef3cb5527f7/chia/util/bech32m.py#L113

**Comment by madMAx43v3r** [comment]
https://github.com/dcdpr/libbech32

**Comment by FlexiMiners** [comment]
So it seems if you use your contract address (P2 Singleton), the hash it creates for the pool is incorrect, this is why partials never get submitted

```
2021-06-24T02:21:21.274 farmer chia.farmer.farmer         : INFO     Did not find pool info for 000c010000000000000d0a00000000002300f40000e000000002000000d00500
2021-06-24T04:55:46.169 farmer chia.farmer.farmer         : INFO     Did not find pool info for 000c010000000000000d0a00000000002300f40000e000000002000000d00500
2021-06-24T15:43:11.827 farmer chia.farmer.farmer         : INFO     Did not find pool info for 000c010000000000000d0a00000000002300f40000e000000002000000d00500
```

**Comment by madMAx43v3r** [comment]
yes, you need to convert the address to the hex hash, but I will fix it, such that you can specify the address directly

**Comment by FlexiMiners** [comment]
> 
> 
> yes, you need to convert the address to the hex hash, but I will fix it, such that you can specify the address directly

Fixed?

**Comment by maxpla3** [comment]
Does this chia_plot branch support pool plots already? Can I create pool plots and use them in pools on the testnet?

**Comment by FlexiMiners** [comment]
> 
> 
> Does this chia_plot branch support pool plots already? Can I create pool plots and use them in pools on the testnet?

I am currently testing with the "Contract Address" converted using the following link:
https://www.chiaexplorer.com/tools/address-puzzlehash-converter

remember to remove the "0x" from the address when specifying it in the -z option

You also have to ensure you pull the pool-puzzle branch as it is not in the main release

Would be good if we could specify K25 plots in testnet9 with MadMax too :)

**Comment by FlexiMiners** [comment]
> 
> 
> > Does this chia_plot branch support pool plots already? Can I create pool plots and use them in pools on the testnet?
> 
> I am currently testing with the "Contract Address" converted using the following link:
> https://www.chiaexplorer.com/tools/address-puzzlehash-converter
> 
> remember to remove the "0x" from the address when specifying it in the -z option
> 
> You also have to ensure you pull the pool-puzzle branch as it is not in the main release
> 
> Would be good if we could specify K25 plots in testnet9 with MadMax too :)

Verified, just got my first partial from MadMax created plot using the hash generated from the link in my previous reply

**Comment by maxpla3** [comment]
> Verified, just got my first partial from MadMax created plot using the hash generated from the link in my previous reply
Very nice! This gives me hope that I can use this plotter to replot everything without SSDs.

**Comment by tdstkt** [comment]
Each pool has /pool_info endpoint
https://pool.xchpool.org/pool_info
you can get puzzle hash from here

**Comment by madMAx43v3r** [comment]
awesome, I'll do the conversion now

**Comment by madMAx43v3r** [comment]
ok try it now, with contract address given via `-c xch1...`

**Comment by hancooo** [comment]
> ok try it now, with contract address given via `-c xch1...`

Tried with as it is printed from 'chia plotnft show' as txch... also tried removing the 't':

`(venv) testnet@chia-testnet:~/chia-plotter$ ./build/chia_plot -r 10 -t /home/testnet/farm/temp/ -2 /mnt/ram/ -d /home/testnet/farm/plots/ -n 1 -p aa632165643432794e42a2527f04c7384678cbab98f7be1ec9f539ac3b5a8b81e30133f67c6666ec25db973f38a9d9ad -f 86bffc8d55cf0d2f8635741669fc90a9e3a7ab78c2f23062838b23648097e08699a3b6e35afd9f8dcebf94374f8fd3c1 -c xch1vajshwzjnadl8xu73nqh2fxl3jhnvta5fmx2f4ygytgqx4w5w9mq2ds75k
terminate called after throwing an instance of 'std::logic_error'
  what():  invalid contract address (!xch): xch1vajshwzjnadl8xu73nqh2fxl3jhnvta5fmx2f4ygytgqx4w5w9mq2ds75k
Aborted (core dumped)
(venv) testnet@chia-testnet:~/chia-plotter$ ./build/chia_plot -r 10 -t /home/testnet/farm/temp/ -2 /mnt/ram/ -d /home/testnet/farm/plots/ -n 1 -p aa632165643432794e42a2527f04c7384678cbab98f7be1ec9f539ac3b5a8b81e30133f67c6666ec25db973f38a9d9ad -f 86bffc8d55cf0d2f8635741669fc90a9e3a7ab78c2f23062838b23648097e08699a3b6e35afd9f8dcebf94374f8fd3c1 -c xch1vajshwzjnadl8xu73nqh2fxl3jhnvta5fmx2f4ygytgqx4w5w9mq2ds75k
terminate called after throwing an instance of 'std::logic_error'
  what():  invalid contract address (!xch): xch1vajshwzjnadl8xu73nqh2fxl3jhnvta5fmx2f4ygytgqx4w5w9mq2ds75k
Aborted (core dumped)`

**Comment by madMAx43v3r** [comment]
ok try again, didn't know it begins with `txch`

**Comment by madMAx43v3r** [comment]
also pool public key is not needed when using contract address

**Comment by kobaltz** [comment]
> ok try again, didn't know it begins with `txch`

I think that is just for the test network and not the mainnet. The main net should use xch, not txch

**Comment by madMAx43v3r** [comment]
makes sense! it will accept both for now.

**Comment by kobaltz** [comment]
cool. i'll update when I get a moment. I manually removed the check so I could plot on the mainnet. BTW, thanks so much for your work and maintenance on this project!

**Comment by altendky** [comment]
> also pool public key is not needed when using contract address

I'm not sure what the behavior is here presently but, FYI, the Chia Network plotter exits with an error message if you specify both.

**Comment by garcha** [comment]
pools docs: https://github.com/Chia-Network/pool-reference

**Comment by mariano54** [comment]
Please take a look at:
https://github.com/madMAx43v3r/chia-plotter/issues/728

**Comment by mariano54** [comment]
Also, txch and xch are both just for display purposes (and slightly different checksum), however, they both map to the same puzzle_hash, so they can be used interchangeably.

**Comment by garcha** [comment]
https://github.com/Chia-Network/chia-blockchain/commit/c11027fb2c74eb80de701ba30137976b0f138196

"During development, there were changes to the plot NFT so portable pool plots (those made with the previously unsupported `-c` option to `chia plots create`) using code prior to this release will be invalid on mainnet."

Will any further changes be needed?

**Comment by madMAx43v3r** [comment]
I checked the changes, no, not to the plotter itself, you may need to create a new NFT though

**Comment by fermosan** [comment]
Heads up. Looks like release of 1.2.0 will be today. 
[https://github.com/Chia-Network/chia-blockchain/commit/88b4dd9ac46a2e1ab847771817ba03e6796efaca](url)

**Comment by VertiHydro** [comment]
@madMAx43v3r  1.2.0 is out - https://github.com/Chia-Network/chia-blockchain/releases/tag/1.2.0
Time to merge into master maybe?

**Comment by JordyBaylac** [comment]
> I checked the changes, no, not to the plotter itself, you may need to create a new NFT though

so do you mean madmax is ok as it is for this 1.2 version? Can I create a new NFT for new plots and still farm previous pool plots in same node?

**Comment by gairom** [comment]
Yes, you should be fine, they confirmed that there were no changes to the NFT so all plots are valid and you don't need to create a new NFT.
+1 to merge to master...

**Pull request merged**
